### ISSUE TITLE
[Bug] Terrain Collision is Ignored

### ISSUE THREAD

**Issue by bidaumm** [ersh1/BG3_NativeCameraTweaks#1]
As per above, with the mod running  the camera will clip through terrain when tilted all the way down.
I would expect this is also happening with all forms of collision but haven't tested

**Comment by ersh1** [comment]
Sorta fixed in 2.0.0. Not real collision detection, but it does collide with a plane at the character's feet.

**Comment by Foul-Tarnished** [comment]
> Sorta fixed in 2.0.0. Not real collision detection, but it does collide with a plane at the character's feet.

Do you know how the other mod did it ?
The BG3ModCam.exe or whatever

Pretty sure it had collision with the ground, maybe even more precise than 2.0.0

I mean, the game does have collision for the camera by default, couldn't you just use it instead of creating an invisible mesh at the character feet or whatever ?
