### ISSUE TITLE
Disable moded camera in fight or turn based mode

### ISSUE THREAD

**Issue by Ferunelli** [ersh1/BG3_NativeCameraTweaks#3]
While in turn based mode, moded camera works awful. It flies somewhere and it's just uncontrolled. Need to disable mode camera in turn based mode and switch back to normal cam

**Comment by ersh1** [comment]
Exploration and combat settings are separated in 2.0.0

**Comment by Foul-Tarnished** [comment]
> Exploration and combat settings are separated in 2.0.0

I think he's also talking of the tactical camera when you press "o".
It change the FoV and the camera rotation anglw is just weird.

idk if it's best to didable this mode, or to force tge camera to be top-down only when this mode is enabled, otherwise you don't know in which mode your are (except that the FoV is weird)

**Comment by ersh1** [comment]
Tactical cam is now separated as well thanks to the contribution from [BoredDan](https://github.com/BoredDan).
